fail_fast: true

exclude: |
  (?x)^(
    .*/(snapshots)/.*|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.13.13
    hooks:
      - id: typos

  # - repo: local
  #   hooks:
  #     - id: cargo-fmt
  #       name: cargo fmt
  #       entry: cargo +nightly fmt --
  #       language: system
  #       types: [rust]
  #       pass_filenames: false

  #     - id: cargo-clippy
  #       name: cargo clippy
  #       language: system
  #       types: [rust]
  #       pass_filenames: false
  #       entry: cargo clippy --features generate,chrono,time,emit -- -D warnings
