[package]
name = "kintsu-testing"
edition = "2024"
publish = false
version.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
insta = { workspace = true, features = ["yaml", "filters"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

