

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

column_sorting = "ordinal_position"
with_docs = true

[migrations_directory]
dir = "migrations"
