type = "struct@v1"
name = "SomeStructWithEnum"
namespace = "abc.corp.test"
version = 1

[fields.enum_value]
name = "enum_value"
namespace = "abc.corp.test"
description = "field doc"
optional = false

[fields.enum_value.type.compound_type]
kind = "enum"
ref = "SomeEnum"
