[package]
name = "kintsu-cli-core"
edition = "2024"
version.workspace = true
license-file.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
console = { workspace = true }
indicatif = { workspace = true }
