version = "v1"

[package]
name = "abc-corp"
description = "abc foo package"
version = "0.1.0"
authors = []
homepage = "https://github.com/joshua-auchincloss/kintsu"

[dependencies]
bar-corp = { path = "../bar-corp" }
