name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NEXTEST_PROFILE: ci
  RUSTFLAGS: "-Awarnings"
  RUSTDOCFLAGS: "-Awarnings"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        # note: i would love to test on macos-16-arm64, but github runners have qemu virtualization issues with m1
        # so until these are fixed (which probably wont happen), we use macos-26 which uses arm64 hardware + intel variations
        runner: [ubuntu-latest, macos-26, macos-15-intel] #, windows-latest]
    steps:
      - name: Free Disk Space
        if: runner.os == 'Linux'
        run: |
          curl https://raw.githubusercontent.com/apache/flink/refs/heads/master/tools/azure-pipelines/free_disk_space.sh | bash

      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - name: Set up Docker
        if: matrix.runner != 'macos-26'
        uses: docker/setup-docker-action@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable, nightly
          components: cargo, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ matrix.runner }}
          cache-all-crates: true
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-insta
          cargo binstall -y --force cargo-nextest

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Test Generation
        run: |
          mise config-sync
          mise gen-a

      - name: Cargo Test
        id: cargo_test
        run: |
          mise test

      - name: Upload snapshots of failed tests
        if: ${{ failure() && steps.cargo_test.outcome == 'failure' }}
        uses: actions/upload-artifact@v6
        with:
          name: failed-snapshots
          path: "**/snapshots/*.snap.new"

  coverage:
    name: Coverage
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
    steps:
      - name: Free Disk Space
        run: |
          curl https://raw.githubusercontent.com/apache/flink/refs/heads/master/tools/azure-pipelines/free_disk_space.sh | bash

      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo, rustfmt, llvm-tools-preview
          toolchain: stable, nightly

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: coverage-${{ matrix.runner }}
          cache-all-crates: true
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-llvm-cov
          cargo binstall -y --force cargo-nextest

      - name: Run coverage
        run: mise run coverage

      - name: Upload coverage reports
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
