name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NEXTEST_PROFILE: ci
  RUSTFLAGS: "-Awarnings"
  RUSTDOCFLAGS: "-Awarnings"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ matrix.runner }}
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-insta
          cargo binstall -y --force cargo-nextest

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Test Generation
        run: |
          mise config-sync
          mise gen-a

      - name: Cargo Test
        id: cargo_test
        run: |
          mise test

      - name: Upload snapshots of failed tests
        if: ${{ failure() && steps.cargo_test.outcome == 'failure' }}
        uses: actions/upload-artifact@v6
        with:
          name: failed-snapshots
          path: "**/snapshots/*.snap.new"

  coverage:
    name: Coverage
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo,llvm-tools-preview
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: coverage-${{ matrix.runner }}
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-llvm-cov

      - name: Run coverage
        run: mise run coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
        with:
          verbose: true
          fail_ci_if_error: true
